name: Build and deploy Node.js app to Azure Function App

on:
  push:
    branches:
      - feature/new-functionality
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
    
    - name: 'Configure WEBSITE_RUN_FROM_PACKAGE setting'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az functionapp config appsettings set \
            --name $AZURE_FUNCTIONAPP_NAME \
            --resource-group $AZURE_RESOURCE_GROUP \
            --settings WEBSITE_RUN_FROM_PACKAGE=1
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: 'npm install'
      run: npm install
         
    - name: 'Deploy to Azure Function'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'test-order'
                # slot-name: 'staging'  # Add this line for staging deployment
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_30351266894A420A9978EFAE62A31D31 }}
                # publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_staging }}



                