# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - orderSlack

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Required permissions for OIDC authentication
permissions:
  id-token: write
  contents: read

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 'Install dependencies and build'
        run: |
          npm ci --only=production
          npm run build --if-present

      - name: 'Create optimized deployment package'
        run: |
          # Remove unnecessary files for smaller package
          rm -rf node_modules/.cache
          rm -rf .git
          rm -rf test
          rm -rf coverage
          # Create deployment package excluding unnecessary files
          zip -r release.zip . -x "*.git*" "*.vscode*" "*test*" "*.md" ".env*" "coverage/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # Required for OIDC
      contents: read
    environment: production

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Login to Azure using OIDC'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'orderSlack'
          slot-name: 'Production'
          package: 'release.zip'
          respect-funcignore: true
          scm-do-build-during-deployment: false