# Example of what Azure will create in .github/workflows/
name: Build and deploy Node.js app to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    
    - name: 'npm install and build'
      run: |
        npm install
        npm run build
         
    - name: 'Deploy to Azure Function'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'orderSlack'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_30351266894A420A9978EFAE62A31D31 }}
          
        # Authentication will use the managed identity